name: Deploy
on:
  push:
    braches:
    - main
workflow_dispatch:

job:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: action/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          usename: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create , env file
      run: 
        echo "VITE_REACT_API_URL=http://localhost:3000/api/" >> .env

      -name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Web_Numerical_Method_Client/Dockerfile
        push: true
        tags: tanabordeee/numerical-client:latest